services:
  db:
    image: postgres:16
    container_name: app-postgres
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  mailpit:
    image: axllent/mailpit:latest
    container_name: mailpit
    ports:
      - "8025:8025" # web UI
      - "1025:1025" # SMTP

  backend:
    container_name: backend-core
    build:
      context: .
      dockerfile: backend-core/src/main/docker/Dockerfile.jvm
    ports:
      - "8080:8080"
    environment:
      # Quarkus datasource primjer
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://db:5432/appdb
      QUARKUS_DATASOURCE_USERNAME: appuser
      QUARKUS_DATASOURCE_PASSWORD: apppass
      QUARKUS_MAILER_HOST: mailpit
      QUARKUS_MAILER_PORT: 1025
      PLAGSCAN_API_URL: http://backend-plagscan:8080
    volumes:
      - //var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - db

  backend-plagscan:
    container_name: backend-plagscan
    build:
      context: .
      dockerfile: backend-plagscan/src/main/docker/Dockerfile.jvm
    ports:
      - "8081:8080"

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    environment:
      API_URL: ""
      PLAGSCAN_REPORT_URL: ""
      PLAGSCAN_REPORT_VIEWER_URL: ""
    depends_on:
      - backend

  cpp-compile-image:
    profiles: [ "build-sandbox" ]
    build:
      context: ./cpp-compile
      dockerfile: Dockerfile
    image: cpp-compile:latest
    entrypoint: [ "true" ]

  cpp-run-image:
    profiles: [ "build-sandbox" ]
    build:
      context: ./cpp-run
      dockerfile: Dockerfile
    image: cpp-run:latest
    entrypoint: [ "true" ]



volumes:
  pgdata:
