mp.jwt.verify.issuer=code-evaluation
mp.jwt.verify.publickey.location=publicKey.pem
smallrye.jwt.sign.key.location=privateKey.pem

# Datasource
quarkus.datasource.db-kind=postgresql
%dev.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/appdb
%dev.quarkus.datasource.username=appuser
%dev.quarkus.datasource.password=apppass
%prod.quarkus.datasource.jdbc.url=${QUARKUS_DATASOURCE_JDBC_URL}
%prod.quarkus.datasource.username=${QUARKUS_DATASOURCE_USERNAME}
%prod.quarkus.datasource.password=${QUARKUS_DATASOURCE_PASSWORD}

# Liquibase
quarkus.liquibase.migrate-at-start=true
quarkus.liquibase.change-log=db/changelog/db.changelog-master.xml

#CORS
quarkus.http.cors.enabled=true
quarkus.http.cors.origins=http://localhost:4200
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.headers=Authorization,Content-Type,Accept,Origin,X-Requested-With
quarkus.http.cors.exposed-headers=Authorization
quarkus.http.cors.access-control-allow-credentials=true

#Mail
quarkus.mailer.from=test@lokalno.dev
quarkus.mailer.host=localhost
quarkus.mailer.port=1025
quarkus.mailer.username=
quarkus.mailer.password=
quarkus.mailer.ssl=false
quarkus.mailer.start-tls=DISABLED
quarkus.mailer.mock=false

#HTTP
quarkus.http.access-log.enabled=true
quarkus.http.access-log.pattern="%r" %s %b %D